required = ["github.com/jteeuwen/go-bindata/go-bindata"]

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.11.1"

[[constraint]]
  branch = "master"
  name = "github.com/jteeuwen/go-bindata"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.0.0"

[[constraint]]
  name = "gopkg.in/olivere/elastic.v6"
  version = "6.1.4"
