version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Clever/ddb-to-es
    docker:
    - image: circleci/golang:1.10.3-stretch
    - image: levlaz/elasticsearch-docker-ci:5.1.1
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - run:
        command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
        name: Clone ci-scripts
    - checkout
    - setup_remote_docker
    - run:
        command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
        name: Set up CircleCI artifacts directories
    - run: make install_deps
    - run: CMD=dynamodb APP_NAME=ddb-to-es make build
    - run: make test
    - run: $HOME/ci-scripts/circleci/catapult-publish-lambda ddb-to-es
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS ddb-to-es clever-dev no-confirm-deploy; fi;
    - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then $HOME/ci-scripts/circleci/dapple-deploy $DAPPLE_URL $DAPPLE_USER $DAPPLE_PASS ddb-to-es production confirm-then-deploy; fi;
